version: "3"
services:
  db:
    image: postgres:15.3-alpine@sha256:58a4e7ae605e8e247180ebba1cc3758ab20677e9a5221ab3150a74f47938b8a1
    environment:
      POSTGRES_USER: spaceship
      POSTGRES_PASSWORD: to_1nf1n1ty_And_Bey0nd
  backend:
    build: .
    image: spaceship:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/spaceship
      SPRING_DATASOURCE_USERNAME: spaceship
      SPRING_DATASOURCE_PASSWORD: to_1nf1n1ty_And_Bey0nd
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
    ports:
      - "8080:8080"
    depends_on:
      - db