name: Deploy

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker images
        run: |
          docker buildx build --platform linux/amd64 --tag jozsefkiss90/spaceship-frontend:latest --file Dockerfile .
          docker buildx build --platform linux/amd64 --tag jozsefkiss90/spaceship-backend:latest --file Dockerfile .

          docker push jozsefkiss90/spaceship-frontend:latest
          docker push jozsefkiss90/spaceship-backend:latest

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.7fb355a5-f8dd-4c30-930b-0113b65bdafb}}
          heroku_app_name: spaceship
          heroku_email: jozsefkiss90@gmail.com
          usedocker: true
          docker_image: your-username/spaceship-backend:latest
